version: '3'
# Other docker-compose examples in /examples

services:
  minecraft:
    image: craftignite/minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - "mc:/data"
    environment:
      EULA: "TRUE"
      VERSION: "1.16"
    restart: always
    cap_add:
      - NET_ADMIN
      - NET_RAW

volumes:
  mc: {}